P0 avatar alert
manojsarna/manoj-smash-ui-component-lib pull request #1
Opened 2022-01-30 19:18 UTC by manojsarna

2022-01-30 19:27 UTC, iRohitGaur commented on style.css
> +    /* font-family: 'Open Sans', sans-serif; */
remove these comments?

2022-01-30 19:27 UTC, iRohitGaur commented on style.css
> +
give consistent spacing between classes

2022-01-30 19:29 UTC, iRohitGaur commented on style.css
> + /* if want to provide box-sizing:content-box */
ok?

2022-01-30 19:31 UTC, iRohitGaur approved these changes
Awesome work! cleanup required. Good to merge after

2022-01-30 20:04 UTC, PuneetP16 commented
You have given container element width 100vh instead of 100% and max-width 120rem in the body element which is causing the horizontal scroll bar to appear at the bottom. 
Solution: change container width to 100% and remove max-width from the body.

2022-01-30 20:43 UTC, m26unkwn commented
hey, Manoj you can use a light green color for the tags 
![image](https://user-images.githubusercontent.com/46845822/151717093-5c470821-9d61-44bd-bd0b-afcde58bb474.png)
and a grey color for text. it's too bright for the eyes.

2022-01-30 20:44 UTC, m26unkwn commented
alert and avatar design is too good.

2022-01-31 04:33 UTC, deekshithmd commented
looks good for me...

2022-01-31 04:59 UTC, rahulyadav139 commented on style.css
> +    padding:2rem 2rem;
The second padding value is redundant (if it is similar to the previous one).

2022-01-31 05:31 UTC, rahulyadav139 commented on style.css
> +
Awesome. The root is loaded with CSS variables to ease out. Codes are reliable and arranged in nature.

2022-01-31 08:00 UTC, Ramandeep9898 commented
looks gud to me:) love the colors

2022-01-31 08:00 UTC, gauravsinhaweb requested changes

2022-01-31 08:00 UTC, gauravsinhaweb commented on index.html
> +                        <a class="link-text link-text-info">Please Check!</a>
I have opted few minor points that can be improved:
1. The <a> tag in HTML is used to create a hyperlink on the webpage, you can use `href` in <a> tag for good coding practices. 
2. The Avatar image size is too large, which can affect the performance of the website. You can reduce the image height width to whatever it requires.

overall Nice work done, LGTM to merge changes.

2022-01-31 09:33 UTC, j24m commented
Looks clean, the color combination looks beautiful.

2022-01-31 13:03 UTC, veereshbv04 commented
There is horizontal scroll bar comming in deploy preview, I guess this can be corrected now

2022-02-01 15:53 UTC, merged