comp: badges and buttons added with new designs
manojsarna/manoj-smash-ui-component-lib pull request #2
Opened 2022-02-02 20:55 UTC by manojsarna

2022-02-02 21:08 UTC, PuneetP16 approved these changes
Nice clean and consistent code.

2022-02-02 21:13 UTC, rahulyadav139 commented
Code is readable and clean. Animations are subtle. Great work.

2022-02-02 21:31 UTC, mehulsatardekar requested changes

2022-02-02 21:31 UTC, mehulsatardekar commented on lib/Components/Badges/badges.css
> +.av-badge{
The naming convention can be improved

2022-02-02 21:41 UTC, mehulsatardekar commented
Other than that code is readable and UI is elegant

2022-02-03 03:16 UTC, iRohitGaur commented on lib/Components/Alerts/alerts.css
> +
suggestion: keep consistency in spacing

2022-02-03 03:17 UTC, iRohitGaur commented on lib/Components/Alerts/alerts.css
> +    height: 2rem; */
remove commented code

2022-02-03 03:20 UTC, iRohitGaur commented on lib/Components/Badges/badges.css
> +    padding: 0.5rem;
suggestion: you can use px value for less than 10px

2022-02-03 03:21 UTC, iRohitGaur approved these changes
Great work! Good to merge 👍🏻

2022-02-03 08:47 UTC, m26unkwn commented
great work Manoj buttons are so nice.

2022-02-03 08:47 UTC, m26unkwn approved these changes

2022-02-03 10:51 UTC, Ramandeep9898 commented
loved that green color... and images :0

2022-02-03 11:00 UTC, saurabhchirde approved these changes
Everything looks good to merge.

2022-02-03 11:00 UTC, saurabhchirde commented on lib/Components/Alerts/alerts.js
> +// btnID.addEventListener("click",()=>console.log("clicked"));
Remove commented code.

2022-02-03 23:22 UTC, merged